name: Build and Release

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        go-version: [1.21.5]
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Check out code
        uses: actions/checkout@v2
      - name: Build
        run: |
          env GOOS=${{ matrix.platform.os }} GOARCH=${{ matrix.platform.arch }} go build -v -o sbstck-dl-${{ matrix.platform.os }}-${{ matrix.platform.arch }}
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: sbstck-dl-${{ matrix.os }}
          path: sbstck-dl-${{ matrix.os }}
